

services:
  laravel:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    networks:
      - my_shared_network
    ports:
      - "6003:80"



networks:
  my_shared_network:
    external: true

